"""initial schema

Revision ID: 8468d562d904
Revises: 
Create Date: 2026-07-28 23:12:27.542844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8468d562d904'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('aspect_preset', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_cost_credits', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('kie_task_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('cost_credits', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['generation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_tasks')
    op.drop_table('generation_batches')
    # ### end Alembic commands ###
